Feature/teamgreen 67
vastafi/Module pull request #22
Opened 2021-05-26 18:50 UTC by CiobanuCorina

Cart page and cart widget, with add/delete buttons and amount changing

2021-05-27 13:33 UTC, aharabara requested changes

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
Почему не использовать шрифты?

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +        <tr class="item">
Вы можете использовать что-то типа data-prototype, но это пока не обязательно, может я позже попрошу это сделать

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +    if (window.location.href === 'http://localhost:8000/cart') {
используется абсолютный url. Если я попытаюсь запустить ваш проект у себя на машине он может не заработать правильно, найдите другой вариант для сравнения вашего текущего URL

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +    let url = "http://localhost:8000/api/v1/cart/" + productCode;
абсолютный url, надо от него избавиться

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +        location.reload(true);
зачем делать reload после удаления продукта из корзины?

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +    if($(location).attr("href") === 'http://localhost:8000/cart/'){
абсолютный url

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +        document.querySelectorAll('.amount').forEach(function (element, index) {
Что делает эта часть кода?

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +    let url = "http://localhost:8000/api/v1/cart/";
абсолютный url

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +        fetchCart($(this).val(), $(this).parent('td').siblings('td').children('button').data('prod-code')).then(function (res) {
` $(this).parent('td').siblings('td').children('button').data('prod-code')` <- неплохо, но может легче будет хранить product code в атрибуте самого input или ближайшего `tr` в котором хранится вся инфа продукта

2021-05-27 13:33 UTC, aharabara commented on public/assets/main/js/cart.js
> +                console.log("You died.");
если вам не нужен catch, то его не обязательно указывать

2021-05-27 13:33 UTC, aharabara commented on src/Controller/Api/CartController.php
> +        foreach ($cart as $item){
`$products = $productRepository->findBy(['code' => array_column($cart->getItems(), 'code'));`
получи все продукты перед тем как выполнить `foreach` и тогда запрос к БД будет только один.

2021-05-27 13:33 UTC, aharabara commented on src/Controller/Api/CartController.php
> +            $stock = $product->getAvailableAmount() + ($cart->getItems())[array_search($productCode, array_map(function($item){
лучше 
`array_column($cart->getItems(), 'amount', 'code')[$productCode];` 
вместо 
```
$cart->getItems())[array_search($productCode, array_map(function($item){
        return $item['code'];
    }, $cart->getItems()))]['amount']
```

2021-05-27 13:33 UTC, aharabara commented on src/Controller/Api/CartController.php
> +            $product->setAvailableAmount($stock - $amount);
обновление стока надо делать только после того, как кто-то совершил заказ, иначе любой человек может забронировать всё в своей корзине и ваш сайт перестанет работать

2021-05-27 13:33 UTC, aharabara commented on templates/product/products.html.twig
> +                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
Может лучше использовать шрифты?

2021-05-27 15:02 UTC, CiobanuCorina commented on public/assets/main/js/cart.js
> +        document.querySelectorAll('.amount').forEach(function (element, index) {
Когда пользователь заходит на страницу корзины, количество заменяется на поле type number чтобы можно было изменить её. А forEach ставит значения поля ранее выбранное пользователем количество.

2021-06-01 17:55 UTC, aharabara approved these changes

2021-06-01 17:55 UTC, aharabara commented on .idea/ProductModule.iml
> +    <orderEntry type="library" name="jquery-3.2.1.slim" level="application" />
Надо удалить из репозитория эту папку

2021-06-01 17:55 UTC, aharabara commented on src/Entity/Order.php
> +        $this->user = new ArrayCollection();
Один заказ может принадлежать одному пользователю
Одному пользователю может принадлежать много заказов.
Если ты инициализируешь  `$this->user` с помощью `ArrayCollection`, то тут точно что-то неправильно работает

2021-06-01 17:55 UTC, aharabara commented on src/Entity/Order.php
> +        $this->user = new ArrayCollection();
Могу предположить что это лишняя линия и её можно просто удалить

2021-06-02 11:17 UTC, merged